// Code generated by mockery v1.0.0
package mocks

import context "context"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// QueryExecutor is an autogenerated mock type for the QueryExecutor type
type QueryExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, namespace, sqlQuery, w
func (_m *QueryExecutor) Execute(ctx context.Context, namespace string, sqlQuery string, w http.ResponseWriter) error {
	ret := _m.Called(ctx, namespace, sqlQuery, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, http.ResponseWriter) error); ok {
		r0 = rf(ctx, namespace, sqlQuery, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
