// Code generated by mockery v1.0.0
package mocks

import common "github.com/uber/aresdb/memstore/common"
import mock "github.com/stretchr/testify/mock"

// SchemaManager is an autogenerated mock type for the SchemaManager type
type SchemaManager struct {
	mock.Mock
}

// GetTableSchemaReader provides a mock function with given fields: namespace
func (_m *SchemaManager) GetTableSchemaReader(namespace string) (common.TableSchemaReader, error) {
	ret := _m.Called(namespace)

	var r0 common.TableSchemaReader
	if rf, ok := ret.Get(0).(func(string) common.TableSchemaReader); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.TableSchemaReader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields:
func (_m *SchemaManager) Run() {
	_m.Called()
}
