// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// EnumUpdater is an autogenerated mock type for the EnumUpdater type
type EnumUpdater struct {
	mock.Mock
}

// UpdateEnum provides a mock function with given fields: table, column, enumList
func (_m *EnumUpdater) UpdateEnum(table string, column string, enumList []string) error {
	ret := _m.Called(table, column, enumList)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string) error); ok {
		r0 = rf(table, column, enumList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
