// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import shard "github.com/m3db/m3/src/cluster/shard"

// ShardSet is an autogenerated mock type for the ShardSet type
type ShardSet struct {
	mock.Mock
}

// All provides a mock function with given fields:
func (_m *ShardSet) All() []shard.Shard {
	ret := _m.Called()

	var r0 []shard.Shard
	if rf, ok := ret.Get(0).(func() []shard.Shard); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]shard.Shard)
		}
	}

	return r0
}

// AllIDs provides a mock function with given fields:
func (_m *ShardSet) AllIDs() []uint32 {
	ret := _m.Called()

	var r0 []uint32
	if rf, ok := ret.Get(0).(func() []uint32); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint32)
		}
	}

	return r0
}
