// Code generated by mockery v1.0.0
package mocks

import client "github.com/uber/aresdb/datanode/client"
import mock "github.com/stretchr/testify/mock"
import topology "github.com/uber/aresdb/cluster/topology"

// Peer is an autogenerated mock type for the Peer type
type Peer struct {
	mock.Mock
}

// BorrowConnection provides a mock function with given fields: fn
func (_m *Peer) BorrowConnection(fn client.WithConnectionFn) error {
	ret := _m.Called(fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(client.WithConnectionFn) error); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Peer) Close() {
	_m.Called()
}

// Host provides a mock function with given fields:
func (_m *Peer) Host() topology.Host {
	ret := _m.Called()

	var r0 topology.Host
	if rf, ok := ret.Get(0).(func() topology.Host); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topology.Host)
		}
	}

	return r0
}
