// Code generated by mockery v1.0.0
package mocks

import client "github.com/uber/aresdb/datanode/client"
import mock "github.com/stretchr/testify/mock"

// PeerSource is an autogenerated mock type for the PeerSource type
type PeerSource struct {
	mock.Mock
}

// BorrowConnection provides a mock function with given fields: hostID, fn
func (_m *PeerSource) BorrowConnection(hostID string, fn client.WithConnectionFn) error {
	ret := _m.Called(hostID, fn)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, client.WithConnectionFn) error); ok {
		r0 = rf(hostID, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *PeerSource) Close() {
	_m.Called()
}
