// Code generated by mockery v1.0.0
package mocks

import common "github.com/uber/aresdb/metastore/common"

import mock "github.com/stretchr/testify/mock"

// TableSchemaValidator is an autogenerated mock type for the TableSchemaValidator type
type TableSchemaValidator struct {
	mock.Mock
}

// SetNewTable provides a mock function with given fields: table
func (_m *TableSchemaValidator) SetNewTable(table common.Table) {
	_m.Called(table)
}

// SetOldTable provides a mock function with given fields: table
func (_m *TableSchemaValidator) SetOldTable(table common.Table) {
	_m.Called(table)
}

// Validate provides a mock function with given fields:
func (_m *TableSchemaValidator) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
