//  Copyright (c) 2017-2018 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by mockery v1.0.0
package mocks

import (
	"github.com/stretchr/testify/mock"
	"github.com/uber/aresdb/controller/models"
)

// IngestionAssignmentMutator is an autogenerated mock type for the IngestionAssignmentMutator type
type IngestionAssignmentMutator struct {
	mock.Mock
}

// AddIngestionAssignment provides a mock function with given fields: namespace, IngestionAssignment
func (_m *IngestionAssignmentMutator) AddIngestionAssignment(namespace string, IngestionAssignment models.IngestionAssignment) error {
	ret := _m.Called(namespace, IngestionAssignment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, models.IngestionAssignment) error); ok {
		r0 = rf(namespace, IngestionAssignment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteIngestionAssignment provides a mock function with given fields: namespace, name
func (_m *IngestionAssignmentMutator) DeleteIngestionAssignment(namespace string, name string) error {
	ret := _m.Called(namespace, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(namespace, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHash provides a mock function with given fields: namespace, subscriber
func (_m *IngestionAssignmentMutator) GetHash(namespace string, subscriber string) (string, error) {
	ret := _m.Called(namespace, subscriber)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(namespace, subscriber)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, subscriber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIngestionAssignment provides a mock function with given fields: namespace, name
func (_m *IngestionAssignmentMutator) GetIngestionAssignment(namespace string, name string) (models.IngestionAssignment, error) {
	ret := _m.Called(namespace, name)

	var r0 models.IngestionAssignment
	if rf, ok := ret.Get(0).(func(string, string) models.IngestionAssignment); ok {
		r0 = rf(namespace, name)
	} else {
		r0 = ret.Get(0).(models.IngestionAssignment)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIngestionAssignments provides a mock function with given fields: namespace
func (_m *IngestionAssignmentMutator) GetIngestionAssignments(namespace string) ([]models.IngestionAssignment, error) {
	ret := _m.Called(namespace)

	var r0 []models.IngestionAssignment
	if rf, ok := ret.Get(0).(func(string) []models.IngestionAssignment); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IngestionAssignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateIngestionAssignment provides a mock function with given fields: namespace, IngestionAssignment
func (_m *IngestionAssignmentMutator) UpdateIngestionAssignment(namespace string, IngestionAssignment models.IngestionAssignment) error {
	ret := _m.Called(namespace, IngestionAssignment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, models.IngestionAssignment) error); ok {
		r0 = rf(namespace, IngestionAssignment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
