// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// NamespaceMutator is an autogenerated mock type for the NamespaceMutator type
type NamespaceMutator struct {
	mock.Mock
}

// CreateNamespace provides a mock function with given fields: namespace
func (_m *NamespaceMutator) CreateNamespace(namespace string) error {
	ret := _m.Called(namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListNamespaces provides a mock function with given fields:
func (_m *NamespaceMutator) ListNamespaces() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
