port: 9377
debug_port: 43205
root_path: /tmp/gforcedb3
total_memory_size: 10737418240 # 150gb
query:
  device_memory_utilization: 0.95
  device_choosing_timeout: 10
  # enable timezone column for queries with "timezone": "timezone(city_id)"
  timezone_table:
    table_name: api_cities
  enable_hash_reduction: false

disk_store:
  write_sync: true
meta_store:
  write_sync: true
http:
  max_connections: 300
  read_time_out_in_seconds: 20
  write_time_out_in_seconds: 300 # 5 minutes to write the result

gateway:
  # example controller client configs
  controller:
    address: localhost:6708
    headers:
      RPC-Caller:
        - aresdb-distributed-staging
      RPC-Service:
        - ares-controller-distributed-staging

cluster:
  enable: true
  cluster_name: "dist"

distributed: true

instance:
  id: 3 # will be replaced by env TODO
  namespace: dist
  heartbeat:
    timeout: 10
    interval: 1
  etcd:
    zone: local 
    env: dev
    service: ares-datanode
    etcdClusters:
      - zone: local
        endpoints:
          - 127.0.0.1:2379

redolog:
  namespace: dist
  disk:
    disabled: false
  kafka:
    enabled: false
    surfix: staging
    uns: udg://kloak-lossless
