port: 9474

http:
  max_connections: 300
  read_time_out_in_seconds: 20
  write_time_out_in_seconds: 300 # 5 minutes to write the result

controller:
  address: localhost:6708
  headers:
    RPC-Caller:
      - aresbroker
    RPC-Service:
      - ares-controller

etcd:
  zone: local
  env: dev
  etcdClusters:
    - zone: local
      endpoints:
        - 127.0.0.1:2379

cluster:
  enable: true
  cluster_name: "test"