// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import shard "github.com/uber/aresdb/cluster/shard"
import topology "github.com/uber/aresdb/cluster/topology"

// HostShardSet is an autogenerated mock type for the HostShardSet type
type HostShardSet struct {
	mock.Mock
}

// Host provides a mock function with given fields:
func (_m *HostShardSet) Host() topology.Host {
	ret := _m.Called()

	var r0 topology.Host
	if rf, ok := ret.Get(0).(func() topology.Host); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topology.Host)
		}
	}

	return r0
}

// ShardSet provides a mock function with given fields:
func (_m *HostShardSet) ShardSet() shard.ShardSet {
	ret := _m.Called()

	var r0 shard.ShardSet
	if rf, ok := ret.Get(0).(func() shard.ShardSet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shard.ShardSet)
		}
	}

	return r0
}
