// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import topology "github.com/uber/aresdb/cluster/topology"

// Initializer is an autogenerated mock type for the Initializer type
type Initializer struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *Initializer) Init() (topology.Topology, error) {
	ret := _m.Called()

	var r0 topology.Topology
	if rf, ok := ret.Get(0).(func() topology.Topology); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topology.Topology)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopologyIsSet provides a mock function with given fields:
func (_m *Initializer) TopologyIsSet() (bool, error) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
