// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import topology "github.com/uber/aresdb/cluster/topology"

// MapProvider is an autogenerated mock type for the MapProvider type
type MapProvider struct {
	mock.Mock
}

// TopologyMap provides a mock function with given fields:
func (_m *MapProvider) TopologyMap() (topology.Map, error) {
	ret := _m.Called()

	var r0 topology.Map
	if rf, ok := ret.Get(0).(func() topology.Map); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(topology.Map)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
