// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bootstrap "github.com/uber/aresdb/datanode/bootstrap"
import client "github.com/uber/aresdb/datanode/client"
import mock "github.com/stretchr/testify/mock"
import topology "github.com/uber/aresdb/cluster/topology"

// Bootstrapable is an autogenerated mock type for the Bootstrapable type
type Bootstrapable struct {
	mock.Mock
}

// Bootstrap provides a mock function with given fields: peerSource, origin, topo, topoState, options
func (_m *Bootstrapable) Bootstrap(peerSource client.PeerSource, origin string, topo topology.Topology, topoState *topology.StateSnapshot, options bootstrap.Options) error {
	ret := _m.Called(peerSource, origin, topo, topoState, options)

	var r0 error
	if rf, ok := ret.Get(0).(func(client.PeerSource, string, topology.Topology, *topology.StateSnapshot, bootstrap.Options) error); ok {
		r0 = rf(peerSource, origin, topo, topoState, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
